name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "next/**"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}

    services:
      mysql:
        image: mysql:8.0
        env:
          # DB設定
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true

      - run: go mod download

      - name: Build
        run: go build -v ./...

      # github actions上で使用するデータの作成
      - name: Setup MySQL schema and seed data
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u docker -pdocker sampledb < .sql/createTable.sql
          mysql -h 127.0.0.1 -u docker -pdocker sampledb < .sql/insertData.sql

      - name: Test
        run: go test -v ./repositories

      - name: Vet
        run: go vet ./...
