name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: sampledb
          MYSQL_USER: docker
          MYSQL_PASSWORD: docker
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true

      - run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Create todos table
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u docker -pdocker sampledb < ./createTable.sql

      - name: Insert todos data
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -u docker -pdocker sampledb < ./insertData.sql

      # TODO: Testを追加したら, go testを追加する
      - name: Test
        env:
          DB_USER: docker
          DB_PASSWORD: docker
          DB_DATABASE: sampledb
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: go test -v ./repositories

      - name: Vet
        run: go vet ./...
